### ISSUE TITLE
No topology

### ISSUE THREAD

**Issue by lordofthejars** [skupperproject/gilligan#1]
Hi, I am running skupper in my public cluster, now I'd like to use gilligan, so I compiled everything, at the end I run serve -s build to get the page but I get:

<img width="1404" alt="Screenshot 2020-04-08 at 11 35 41" src="https://user-images.githubusercontent.com/1517153/78769168-400a7c00-798d-11ea-9066-38d471b37387.png">

All the time, do I need to have something into consideration?

**Comment by grs** [comment]
What version of skupper are you running? You need 0.2.0 and then can access the console via the skupper-controller service (or route if running on openshift). When you run `skupper init` you can specify the console-user and console-password, otherwise they will be generated (admin and a random password held in secrets/skupper-console-users). You can also disable authentication by specifying `--console-auth unsecured`. If you are running on openshift you can use oauth against the openshift console by specifying `--console-auth openshift`.

**Comment by lordofthejars** [comment]
aha there is a lot of more things to do. Thanks, I'll look at it.

**Comment by lordofthejars** [comment]
Ok running now thanks.
